In [9]:
# Encapsulation
# + Encapsulation is the process of wrapping data(variables) and methods into single entity
'''
In python we can get encapsulation by private(__) and protected(_) access modifiers
'''
# class Reactangle:  # With out encapsulation
#     height=0
#     width=0
#     def __init__(self):
#         self.height=10
#         self.width=2
#         print(self.height)
#         print(self.width)
        
# rect=Reactangle()
# print(rect.height)


# class Reactangle:    #Private access modifier
#     __height=0
#     __width=0
#     def __init__(self):
#         self.__height=10
#         self.__width=2
#         print(self.__height)
#         print(self.__width)
        
# rect=Reactangle()
# print(rect.height)


class Reactangle:  # private access modifier
    _height=0
    _width=0
    def __init__(self):
        self._height=10
        self._width=2
        print(self._height)
        print(self._width)
        
rect=Reactangle()
print(rect.height)

10
2


AttributeError: 'Reactangle' object has no attribute 'height'

# Abstraction
+ Abstraction is the process of hiding the real implementation of the method by only showing a method to the user
 
+ To create abstract class first we need to `import abc` module.
+ After that we need to `import ABC` class as base class for abstract class.
+ To define any method as abstract method we need to give `@abstractmethod` keyword above our abstractmethod



In [13]:
import abc

from abc import ABC,abstractmethod

# class Ab_class(ABC):
#     def sample(self):
#         print("This is normal method")
#     @abstractmethod
#     def ab_sample(self):
#         pass
    
# class Main(Ab_class):
#     def ab_sample(self):
#         print("This is abstract method")

# obj=Main()
# obj.ab_sample()

class Arith(ABC):
    def __init__(self,a):
        self.a=a
    @abstractmethod
    def add(self):
        pass
    
class outer(Arith):
    def add(self):
        print(self.a+23)
        
obj=outer(3)
obj.add()

26


In [3]:
# Numpy,Pandas and Matplotlib

import numpy as np

array1=np.array([1,23,333])
print(array1)

[  1  23 333]


In [11]:
import numpy as np
data=np.array((12,22,33))
data1=np.array([(1,2,3),(4,5,6)])
print(data1)

[[1 2 3]
 [4 5 6]]


In [9]:
twodArray=np.array([[1,2,3],[4,5,6]])
print(twodArray)

[[1 2 3]
 [4 5 6]]


In [16]:
print(type(twodArray))
print(twodArray.dtype)
print(twodArray.shape)
print(twodArray.size)
print(twodArray.ndim)

<class 'numpy.ndarray'>
int32
(2, 3)
6
2


In [22]:
# create array using range()

array1=np.array(range(0,10,2))
print(array1)

[0 2 4 6 8]


In [29]:
# arange().reshape()
print(np.arange(30,10,-0.5))

[30.  29.5 29.  28.5 28.  27.5 27.  26.5 26.  25.5 25.  24.5 24.  23.5
 23.  22.5 22.  21.5 21.  20.5 20.  19.5 19.  18.5 18.  17.5 17.  16.5
 16.  15.5 15.  14.5 14.  13.5 13.  12.5 12.  11.5 11.  10.5]


In [34]:
result=np.arange(1,21).reshape(2,10)  # [4,5] [5,4] [1,20][20,1][10,2]
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [37]:
# linspace
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [41]:
# ones,zeros
data=np.ones((2,3))
print(data)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
data1=np.zeros((4,5))
print(data1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
data1.fill(24)
data1

array([[24., 24., 24., 24., 24.],
       [24., 24., 24., 24., 24.],
       [24., 24., 24., 24., 24.],
       [24., 24., 24., 24., 24.]])

In [46]:
Allresult=np.array([[1,2,3],[2.3,22.22,4.3],["q","w","R"]])
Allresult

array([['1', '2', '3'],
       ['2.3', '22.22', '4.3'],
       ['q', 'w', 'R']], dtype='<U32')

In [49]:
# Mathematical operations

ar1=np.arange(1,21).reshape(4,5)
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
ar2=np.arange(21,41).reshape(4,5)
ar2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [56]:
print(ar1+ar2)

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
